export const races = [
  { id: "human", name: "Human" },
  { id: "elf", name: "Elf" },
  { id: "dwarf", name: "Dwarf" },
  { id: "orc", name: "Orc" },
  { id: "halfling", name: "Halfling" },
  { id: "goblin", name: "Goblin" },
  { id: "trollkin", name: "Trollkin" },
  { id: "saurian", name: "Saurian", description: "Reptilian humanoids with ancient culture" },
  { id: "kith", name: "Kith", description: "Plant-like humanoids, masters of herbal lore" },
  { id: "naiad", name: "Naiad", description: "Aquatic beings, adept in water magic" },
  { id: "centaur", name: "Centaur", description: "Half-human, half-horse creatures, known for speed and endurance" },
  { id: "pixie", name: "Pixie", description: "Tiny winged folk, skilled in illusion and mischief" },
];

export const edges = [
  { id: "alertness", 
    name: "Alertness", 
    description: "+2 Notice", 
    requirements: "None", 
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:alertness"
  },
  { id: "ambidextrous", 
    name: "Ambidextrous", 
    description: "Ignore -2 penalty for off-hand", 
    requirements: "Agility d8+",
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:alertness"
  },
  { id: "arcaneResistance", 
    name: "Arcane Resistance", 
    description: "-2 to be affected by powers, +2 to resist", 
    requirements: "Spirit d8+", 
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:arcane-resistance"
  },
  { id: "brawny", 
    name: "Brawny", 
    description: "+1 Toughness, load limit is 8x Str", 
    requirements: "Strength d6+", 
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:brawny"
  },
  { id: "fleetFooted", 
    name: "Fleet-Footed", 
    description: "+2 Pace and d10 running die", 
    requirements: "Agility d6+",
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:fleet-footed"
  },
  { id: "hard_to_kill", 
    name: "Hard To Kill", 
    description: "When forced to make Vigor rolls due to Incapacitation, he may ignore his wound modifiers. This only applies to Vigor rolls called for to resist Incapacitation or death.", 
    requirements: "Wild Card, Spirit d8+", 
    type: "Combat",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:hard-to-kill"
  },
  { id: "quick", 
    name: "Quick", 
    description: "Redraw initiative cards of 5 or lower", 
    requirements: "Agility d8+", 
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:quick"
  },
  { id: "rich", 
    name: "Rich", 
    description: "Three times starting funds and $75K annual salary", 
    requirements: "Novice",
    type: "Background",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:rich"
  },
  { id: "rockAndRoll", 
    name: "Rock and Roll!", 
    description: "Ignore full-auto penalty if shooter does not move", 
    requirements: "Seasoned (2), Shooting d8+",
    type: "Combat",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=edges:rock-and-roll"
  },
];

export const hindrances = [
  { id: "allThumbs", 
    name: "All Thumbs", 
    description: "-2 Repair; Break devices on critical failure",
    type: "Minor",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:all-thumbs"
  },
  { id: "anemic", 
    name: "Anemic", 
    description: "-2 to Fatigue tests",
    type: "Minor",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:anemic"
  },
  { id: "arrogant", 
    name: "Arrogant", 
    description: "Your hero doesn't think he's the best–he knows he is. Whatever it is–swordsmanship, kung-fu, running–few compare to his skills and he flaunts it every chance he gets.",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:arrogant"
  },
  { id: "bad_eyes", 
    name: "Bad Eyes", 
    description: "-2 penalty to any Trait roll made to shoot",
    type: "Minor or Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:bad-eyes"
  },
  { id: "big_mouth", 
    name: "Big Mouth", 
    description: "Your character can't keep a secret very well. He reveals plans and gives away things best kept among friends, usually at the worst possible times.",
    type: "Minor",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:big-mouth"
  },
  { id: "blind", 
    name: "Blind", 
    description: "Cannot see; -6 to all actions that rely on vision",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:blind"
  },
  { id: "bloodthirsty", 
    name: "Bloodthirsty", 
    description: "Never take prisoners; -4 to charmisa, but only if cruel habits are known.",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:bloodthirsty"
  },
  { id: "cautious", 
    name: "Cautious", 
    description: "Makes rash decisions and likes to plot things out in detail long before any action is taken. ",
    type: "Minor",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:cautious"
  },
  { id: "clueless", 
    name: "Clueless", 
    description: "-2 Common Knowledge rolls",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:clueless"
  },
  { id: "code_of_honor", 
    name: "Code of Honor", 
    description: " He keeps his word, won't abuse or kill prisoners, and generally tries to operate within his world's particular notion of proper gentlemanly or ladylike behavior.",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:code-of-honor"
  },
  { id: "curious", 
    name: "Curious", 
    description: "Character wants to know about everything",
    type: "Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:curious"
  },
  { id: "death_wish", 
    name: "Death Wish", 
    description: "When there's a chance to complete their goal, they'll do anything—and take any risk–to achieve it.",
    type: "Minor",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:death-wish"
  },
   { id: "delusional", 
    name: "Delusional", 
    description: "Your hero believes something that is considered quite strange by everyone else.",
    type: "Minor or Major",
    link: "https://harrowhawk-neptuna.com/!savage-worlds-deluxe/doku.php?id=hindrances:delusional"
  },
  { id: "elderly", name: "Elderly", description: "Physical attributes decrease but gain skill points" },
  { id: "enemy", name: "Enemy", description: "Character has a recurring nemesis" },
  { id: "greedy", name: "Greedy", description: "Character is significantly motivated by wealth" },
  { id: "pacifist", name: "Pacifist", description: "Will only fight in self-defense or to protect others" }
];

export const skills = [
  { id: "academics", name: "Academics" },
  { id: "athletics", name: "Athletics" },
  { id: "common_know", name: "Common Know" },
  { id: "driving", name: "Driving" },
  { id: "electronics", name: "Electronics" },
  { id: "fighting", name: "Fighting" },
  { id: "hacking", name: "Hacking" },
  { id: "healing", name: "Healing" },
  { id: "intimidation", name: "Intimidation" },
  { id: "language", name: "Language" },
  { id: "notice", name: "Notice" },
  { id: "occult", name: "Occult" },
  { id: "performance", name: "Performance" },
  { id: "piloting", name: "Piloting" },
  { id: "persuasion", name: "Persuasion" },
  { id: "repair", name: "Repair" },
  { id: "research", name: "Research" },
  { id: "riding", name: "Riding" },
  { id: "science", name: "Science" },
  { id: "shooting", name: "Shooting" },
  { id: "stealth", name: "Stealth" },
  { id: "survival", name: "Survival" },
  { id: "taunt", name: "Taunt" },
  { id: "thievery", name: "Thievery" },
];

export const powers = [
  { id: "fireball", name: "Fireball", description: "Launches a ball of fire towards enemies, dealing area damage." },
  { id: "telekinesis", name: "Telekinesis", description: "Moves objects with the power of the mind, allowing for manipulation from a distance." },
  { id: "invisibility", name: "Invisibility", description: "Renders the user invisible to sight, allowing for stealthy movement." },
  { id: "healing", name: "Healing", description: "Restores health and vitality to the user or allies." },
  { id: "flight", name: "Flight", description: "Grants the ability to fly through the air with ease." },
  { id: "teleportation", name: "Teleportation", description: "Instantly transports the user from one location to another." },
  { id: "shapeshifting", name: "Shapeshifting", description: "Allows the user to change their form into that of another creature." },
  { id: "mindControl", name: "Mind Control", description: "Takes control of the minds of others, bending them to the user's will." },
];

export const gearOptions = {
  weapons: [
    { id: "sword", name: "Sword", description: "A sturdy blade for close combat." },
    { id: "bow", name: "Bow", description: "A long-range weapon for skilled archers." },
    { id: "axe", name: "Battle Axe", description: "A heavy weapon capable of dealing devastating blows." },
    { id: "staff", name: "Staff", description: "A versatile weapon used by mages and monks." },
    { id: "dagger", name: "Dagger", description: "A small blade ideal for quick and stealthy attacks." },
  ],
  armor: [
    { id: "chainmail", name: "Chainmail", description: "Protective armor offering decent mobility." },
    { id: "leather", name: "Leather Armor", description: "Light armor for stealth and speed." },
    { id: "plate", name: "Plate Armor", description: "Heavy and durable armor providing maximum protection." },
    { id: "cloak", name: "Cloak", description: "A cloak for camouflage and protection against weather." },
    { id: "helmet", name: "Helmet", description: "Protective headgear to safeguard against head injuries." },
  ],
  items: [
    { id: "potion", name: "Healing Potion", description: "Heals wounds instantly." },
    { id: "torch", name: "Torch", description: "Illuminates dark areas." },
    { id: "scroll", name: "Scroll", description: "A magical scroll containing spells or enchantments." },
    { id: "rope", name: "Rope", description: "Strong and versatile rope for climbing or binding." },
    { id: "lockpick", name: "Lockpick", description: "Tools used for picking locks and disabling traps." },
  ],
};

export const bossGearOptions = {
  weapons: [
    { id: "greatsword", name: "Greatsword", description: "A massive two-handed sword for devastating strikes." },
    { id: "demonblade", name: "Demonblade", description: "An ancient blade forged from demon's bones, infused with dark power." },
    { id: "voidstaff", name: "Staff of the Void", description: "A staff that channels the power of the void, capable of unraveling reality." },
    { id: "chaosclaw", name: "Chaosclaw Gauntlets", description: "Gauntlets crackling with chaotic energy, tearing through reality with each strike." },
    { id: "doomhammer", name: "Doomhammer", description: "A massive hammer pulsating with dark energy, capable of shattering armor with ease." },
    { id: "bloodreaper", name: "Bloodreaper Scythe", description: "A scythe infused with the essence of death, draining the life force from foes." },
  ],
  armor: [
    { id: "dreadplate", name: "Dreadplate Armor", description: "Dark armor adorned with spikes, instilling fear in enemies." },
    { id: "dragonhide", name: "Dragonhide Armor", description: "Armor crafted from the scales of a powerful dragon, granting protection and resilience." },
    { id: "shadowcloak", name: "Shadowcloak", description: "A cloak woven from the shadows, granting the wearer unparalleled stealth." },
    { id: "voidveil", name: "Veil of the Void", description: "A veil that renders the wearer invisible to both sight and magical detection." },
    { id: "soulbound", name: "Soulbound Cuirass", description: "Armor fused with the souls of fallen warriors, granting unmatched resilience." },
    { id: "necroshroud", name: "Necroshroud Robes", description: "Robes woven from the fabric of death itself, granting necromantic powers." },
  ],
  items: [
    { id: "potion", name: "Healing Potion", description: "Heals wounds instantly." },
    { id: "scroll", name: "Scroll of Necromancy", description: "Summons an army of undead to serve the wielder." },
    { id: "amulet", name: "Amulet of Dark Desires", description: "Amulet that corrupts the wearer's enemies, turning them against each other." },
    { id: "banecharm", name: "Banecharm", description: "Charm imbued with curses, weakening foes and draining their vitality." },
    { id: "crystal", name: "Crystal of Time Stop", description: "Crystal that can temporarily halt time, freezing enemies in place." },
    { id: "darkorb", name: "Dark Orb of Annihilation", description: "Orb that unleashes a blast of pure darkness, consuming all in its path." },
  ],
};

export const legendaryGearOptions = {
  weapons: [
    { id: "excalibur", name: "Excalibur", description: "The legendary sword of King Arthur, said to be the most powerful weapon in existence." },
    { id: "mjoelnir", name: "Mjölnir", description: "The hammer of Thor, capable of summoning thunder and lightning." },
    { id: "masamune", name: "Masamune", description: "A katana forged by a legendary swordsmith, possessing unparalleled sharpness and cutting power." },
    { id: "gungnir", name: "Gungnir", description: "The spear of Odin, never missing its target and returning to the wielder's hand." },
    { id: "caladbolg", name: "Caladbolg", description: "A mythical greatsword with the power to cleave mountains and split the seas." },
    { id: "ragnarok", name: "Ragnarok Blade", description: "A blade forged in the fires of the apocalypse, capable of ending worlds." },
  ],
  armor: [
    { id: "adamantite", name: "Adamantite Plate", description: "Armor forged from the mythical metal adamantite, impervious to all but the most powerful attacks." },
    { id: "eternalguard", name: "Eternalguard Shield", description: "A shield blessed by the gods, capable of shielding the wearer from any harm." },
    { id: "celestialrobe", name: "Celestial Robe", description: "Robes woven from starlight and moonbeams, granting the wearer divine protection." },
    { id: "dragonheart", name: "Dragonheart Armor", description: "Armor infused with the essence of a dragon's heart, granting immense strength and resilience." },
    { id: "seraphiccloak", name: "Seraphic Cloak", description: "A cloak imbued with the light of the heavens, rendering the wearer invulnerable to darkness and evil." },
    { id: "shadowbane", name: "Shadowbane Armor", description: "Armor forged from the essence of darkness, granting the wearer mastery over shadows." },
  ],
  items: [
    { id: "elixir", name: "Elixir of Immortality", description: "Grants the drinker eternal life and youth." },
    { id: "relic", name: "Relic of Power", description: "A mystical artifact imbued with ancient magic, granting immense power to its wielder." },
    { id: "orb", name: "Orb of Omniscience", description: "An orb that grants the wielder unlimited knowledge and foresight." },
    { id: "scepter", name: "Scepter of Dominion", description: "A scepter that grants the wielder control over all aspects of existence." },
    { id: "crown", name: "Crown of Kings", description: "A crown that bestows the wearer with unmatched authority and leadership." },
    { id: "phylactery", name: "Phylactery of Lichdom", description: "A phylactery that grants the user eternal undeath and necromantic powers." },
  ],
};

export const moneyOptions = [
  { id: "poor", name: "Poor", amount: "50 Gold", description: "Barely enough to get by." },
  { id: "modest", name: "Modest", amount: "200 Gold", description: "A modest amount to start your adventure." },
  { id: "wealthy", name: "Wealthy", amount: "1000 Gold", description: "Well-funded and ready for anything." },
];

export const personalityTraits = [
  { id: 1, name: "Brave" },
  { id: 2, name: "Cunning" },
  { id: 3, name: "Generous" },
  { id: 4, name: "Loyal" },
  { id: 5, name: "Optimistic" },
  { id: 6, name: "Resourceful" },
  { id: 7, name: "Stubborn" },
  { id: 8, name: "Witty" },
  { id: 9, name: "Adventurous" },
  { id: 10, name: "Compassionate" },
  { id: 11, name: "Diligent" },
  { id: 12, name: "Enthusiastic" },
  { id: 13, name: "Honest" },
  { id: 14, name: "Meticulous" },
  { id: 15, name: "Tactful" },
  { id: 16, name: "Creative" },
  { id: 17, name: "Energetic" },
  { id: 18, name: "Independent" },
  { id: 19, name: "Patient" },
  { id: 20, name: "Resilient" },
];

export const backgrounds = [
  { id: "hermit", name: "Hermit", description: "A recluse who has chosen to live in isolation from society." },
  { id: "pirate", name: "Pirate", description: "A seafaring outlaw who raids ships for treasure and adventure." },
  { id: "acolyte", name: "Acolyte", description: "A devout follower of a religious order, dedicated to serving their deity." },
  { id: "mercenary", name: "Mercenary", description: "A hired soldier or warrior who fights for coin or cause." },
  { id: "noble", name: "Noble", description: "A member of the aristocracy, with wealth, privilege, and social status." },
  { id: "outlaw", name: "Outlaw", description: "A fugitive from the law, living outside of societal norms." },
  { id: "artisan", name: "Artisan", description: "A skilled craftsman or craftswoman, creating goods of value." },
  { id: "scholar", name: "Scholar", description: "An academic or intellectual, dedicated to the pursuit of knowledge." },
  { id: "merchant", name: "Merchant", description: "A trader or businessperson, buying and selling goods for profit." },
  { id: "thief", name: "Thief", description: "A skilled rogue or burglar, adept at stealing and subterfuge." },
  { id: "wanderer", name: "Wanderer", description: "A nomad or traveler, journeying from place to place in search of adventure." },
  { id: "knight", name: "Knight", description: "A noble warrior sworn to uphold chivalry and protect the realm." },
  { id: "hunter", name: "Hunter", description: "A skilled tracker and survivalist, living off the land and hunting wild game." },
  { id: "peasant", name: "Peasant", description: "A commoner working the land, struggling to make ends meet." },
  { id: "bandit", name: "Bandit", description: "A member of a criminal gang, preying on travelers and merchants." },
  { id: "sailor", name: "Sailor", description: "A seafarer experienced in navigating the ocean, working aboard ships." },
  { id: "spy", name: "Spy", description: "A covert operative skilled in espionage and gathering intelligence." },
  { id: "gladiator", name: "Gladiator", description: "A skilled fighter trained to compete in arenas for the entertainment of others." },
  { id: "assassin", name: "Assassin", description: "A trained killer who specializes in stealth and precision strikes." },
  { id: "priest", name: "Priest", description: "A religious leader, guiding and ministering to the faithful of their deity." },
  { id: "explorer", name: "Explorer", description: "An adventurer driven by curiosity, seeking to uncover hidden treasures and lost civilizations." },
  { id: "courtier", name: "Courtier", description: "A member of a royal court, navigating the intrigues and politics of the nobility." },
  { id: "gladiator", name: "Gladiator", description: "A skilled fighter trained to compete in arenas for the entertainment of others." },
  { id: "beastmaster", name: "Beastmaster", description: "A master of taming and controlling wild animals, using them in combat or as companions." },
  { id: "bountyHunter", name: "Bounty Hunter", description: "A relentless pursuer of criminals and fugitives, tracking down targets for a reward." },
  { id: "blacksmith", name: "Blacksmith", description: "A skilled metalworker, forging weapons, armor, and tools at the anvil." },
];

export const secrets = [
  { id: "criminalPast", name: "Criminal Past", description: "The NPC has a history of crime or wrongdoing, which they may be trying to hide from others." },
  { id: "lostLove", name: "Lost Love", description: "The NPC once had a deep romantic connection with someone, but circumstances forced them apart." },
  { id: "familyFeud", name: "Family Feud", description: "The NPC's family is involved in a long-standing feud or conflict with another family or faction." },
  { id: "forbiddenKnowledge", name: "Forbidden Knowledge", description: "The NPC possesses knowledge or information that is considered dangerous or forbidden by society." },
  { id: "identityTheft", name: "Identity Theft", description: "The NPC has assumed a false identity to escape their past or evade pursuit by authorities." },
  { id: "cursedBloodline", name: "Cursed Bloodline", description: "The NPC comes from a family line cursed by dark magic or a supernatural entity, which brings misfortune to all its members." },
  { id: "treacherousAlly", name: "Treacherous Ally", description: "The NPC has a close friend or ally who secretly plots against them or has betrayed them in the past." },
  { id: "mysteriousRelic", name: "Mysterious Relic", description: "The NPC possesses or seeks a powerful artifact or relic with unknown origins and potentially dangerous consequences." },
  { id: "secretSociety", name: "Secret Society", description: "The NPC is a member of a clandestine organization with its own agenda and rituals, hidden from the public eye." },
  { id: "darkPast", name: "Dark Past", description: "The NPC has a traumatic or shameful event in their past that haunts them and influences their actions." },
  { id: "hiddenAgenda", name: "Hidden Agenda", description: "The NPC harbors a secret goal or motive that they pursue covertly, often at odds with their public persona." },
  { id: "ancientProphecy", name: "Ancient Prophecy", description: "The NPC is linked to an ancient prophecy or foretelling that could have profound implications for the world." },
  { id: "enchantedItem", name: "Enchanted Item", description: "The NPC possesses a magical or enchanted item of great power, which they guard closely or seek to exploit." },
  { id: "politicalAmbition", name: "Political Ambition", description: "The NPC harbors ambitions for political power or influence, manipulating events from behind the scenes." },
  { id: "secretExile", name: "Secret Exile", description: "The NPC is in hiding or living in exile, banished from their homeland for a crime or offense." },
  { id: "ancestralLegacy", name: "Ancestral Legacy", description: "The NPC is the heir to a powerful lineage or bloodline, with responsibilities and expectations placed upon them." },
  { id: "fatefulEncounter", name: "Fateful Encounter", description: "The NPC had a significant encounter with a legendary figure or entity that changed the course of their life." },
  { id: "mysteriousPast", name: "Mysterious Past", description: "The NPC's past is shrouded in mystery, with gaps in their memory or conflicting accounts of their history." },
  { id: "supernaturalAffliction", name: "Supernatural Affliction", description: "The NPC suffers from a supernatural affliction or curse that grants them power but comes at a terrible cost." },
  { id: "betrayedTrust", name: "Betrayed Trust", description: "The NPC was betrayed by someone they trusted deeply, leading to a profound loss or trauma." },
  { id: "ancientGuardian", name: "Ancient Guardian", description: "The NPC is tasked with protecting a sacred or ancient site, artifact, or secret from those who would misuse it." },
  { id: "propheticDreams", name: "Prophetic Dreams", description: "The NPC experiences vivid and prophetic dreams that provide glimpses of future events or hidden truths." },
  { id: "lostHeirloom", name: "Lost Heirloom", description: "The NPC seeks a lost family heirloom or artifact of sentimental value, driving them on a quest to recover it." },
  { id: "sinisterPlot", name: "Sinister Plot", description: "The NPC uncovers a sinister plot or conspiracy that threatens the stability of the world, but few believe their warnings." },
  { id: "estrangedFamily", name: "Estranged Family", description: "The NPC is estranged from their family, either by choice or circumstance, and seeks reconciliation or closure." },
  { id: "divineIntervention", name: "Divine Intervention", description: "The NPC receives divine guidance or intervention from a deity or higher power, shaping their destiny." },
  { id: "mysteriousPatron", name: "Mysterious Patron", description: "The NPC is sponsored or supported by a mysterious benefactor with hidden motives and goals." },
];

